# Generated by Django 6.0.1 on 2026-02-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["company", "name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["company", "name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_company_admin",
            field=models.BooleanField(
                default=False, help_text="Is this user a company admin?"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("company", "code"), ("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("company", "code"), ("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="userprofile",
            unique_together={("company", "employee_id")},
        ),
    ]
