# Generated by Django 6.0.1 on 2026-02-08 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username at time of action (preserved even if user deleted)",
                        max_length=150,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the object that was modified",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="String representation of the object at time of action",
                        max_length=500,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what happened"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Previous values before the change (for UPDATE/DELETE)",
                        null=True,
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="New values after the change (for CREATE/UPDATE)",
                        null=True,
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        help_text="List of fields that were changed",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/client user agent string",
                        null=True,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="URL path of the request",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, PUT, DELETE, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the action",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company context at time of action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of object that was modified",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["content_type", "-timestamp"],
                        name="audit_logs_content_594eb8_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_logs_action_f48619_idx",
                    ),
                    models.Index(
                        fields=["company", "-timestamp"],
                        name="audit_logs_company_03f3f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of activity")),
                (
                    "creates",
                    models.IntegerField(
                        default=0, help_text="Number of create actions"
                    ),
                ),
                (
                    "updates",
                    models.IntegerField(
                        default=0, help_text="Number of update actions"
                    ),
                ),
                (
                    "deletes",
                    models.IntegerField(
                        default=0, help_text="Number of delete actions"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(default=0, help_text="Number of view actions"),
                ),
                (
                    "logins",
                    models.IntegerField(default=0, help_text="Number of logins"),
                ),
                (
                    "exports",
                    models.IntegerField(default=0, help_text="Number of exports"),
                ),
                (
                    "total_actions",
                    models.IntegerField(
                        default=0, help_text="Total actions for the day"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_summary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Summary",
                "verbose_name_plural": "User Activity Summaries",
                "db_table": "user_activity_summary",
                "ordering": ["-date", "user"],
                "indexes": [
                    models.Index(
                        fields=["-date", "user"], name="user_activi_date_11ad59_idx"
                    ),
                    models.Index(
                        fields=["company", "-date"],
                        name="user_activi_company_a9a896_idx",
                    ),
                ],
                "unique_together": {("user", "company", "date")},
            },
        ),
    ]
