# Generated by Django 6.0.1 on 2026-01-31 06:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gstin",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="GSTIN"
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="PAN"
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("SUPPLIER", "Supplier"),
                            ("MANUFACTURER", "Manufacturer"),
                            ("SERVICE_PROVIDER", "Service Provider"),
                            ("CONTRACTOR", "Contractor"),
                        ],
                        default="SUPPLIER",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or name",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_categories",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "db_table": "asset_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset_tag",
                    models.CharField(
                        db_index=True,
                        help_text="Unique asset identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="QR Code UUID",
                        unique=True,
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "make",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Manufacturer/Make",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True, help_text="Technical specifications", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ORDERED", "Ordered"),
                            ("IN_STOCK", "In Stock"),
                            ("DEPLOYED", "Deployed"),
                            ("IN_USE", "In Use"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("RETIRED", "Retired"),
                            ("DISPOSED", "Disposed"),
                            ("LOST", "Lost"),
                            ("STOLEN", "Stolen"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("NOT_WORKING", "Not Working"),
                        ],
                        default="GOOD",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "purchase_order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("warranty_start_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                (
                    "warranty_period_months",
                    models.IntegerField(
                        blank=True, help_text="Warranty period in months", null=True
                    ),
                ),
                (
                    "amc_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="AMC Start Date"
                    ),
                ),
                (
                    "amc_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="AMC End Date"
                    ),
                ),
                (
                    "amc_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="AMC Cost",
                    ),
                ),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual depreciation rate (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "useful_life_years",
                    models.IntegerField(
                        blank=True, help_text="Expected useful life in years", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False, help_text="Is this a critical asset?"
                    ),
                ),
                ("is_insured", models.BooleanField(default=False)),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("insurance_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="users.department",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="users.location",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("WARRANTY_CARD", "Warranty Card"),
                            ("AMC_CONTRACT", "AMC Contract"),
                            ("USER_MANUAL", "User Manual"),
                            ("CERTIFICATE", "Certificate"),
                            ("INSURANCE", "Insurance Document"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("document_file", models.FileField(upload_to="asset_documents/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="assets.asset",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Document",
                "verbose_name_plural": "Asset Documents",
                "db_table": "asset_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("ASSIGNED", "Assigned"),
                            ("TRANSFERRED", "Transferred"),
                            ("RETURNED", "Returned"),
                            ("MAINTENANCE", "Sent for Maintenance"),
                            ("REPAIRED", "Repaired"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("LOCATION_CHANGED", "Location Changed"),
                            ("DISPOSED", "Disposed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value (JSON)", null=True
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, help_text="New value (JSON)", null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="assets.asset",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_from",
                        to="users.location",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_to",
                        to="users.location",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset History",
                "verbose_name_plural": "Asset History",
                "db_table": "asset_history",
                "ordering": ["-action_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("ELECTRONIC", "Electronic Assets"),
                            ("IT_TECH", "IT & Technology Assets"),
                            ("FURNITURE", "Furniture & Office Assets"),
                            ("MACHINERY", "Plant, Machinery & Industrial Assets"),
                            ("FACILITY", "Facility & Infrastructure Assets"),
                            ("VEHICLE", "Vehicles & Transportation Assets"),
                            ("SOFTWARE", "Software & Intangible Assets"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("requires_calibration", models.BooleanField(default=False)),
                ("requires_insurance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_types",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
                "db_table": "asset_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assettype",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="amc_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amc_assets",
                to="assets.vendor",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_assets",
                to="assets.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_tag"], name="assets_asset_t_3d9023_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["serial_number"], name="assets_serial__240171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="assets_status_326766_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["location", "department"], name="assets_locatio_94b79f_idx"
            ),
        ),
    ]
