# Generated by Django 6.0.1 on 2026-02-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("core", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("disposal_number", models.CharField(max_length=50, unique=True)),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("SELL", "Sell"),
                            ("SCRAP", "Scrap"),
                            ("DONATE", "Donate"),
                            ("DESTROY", "Destroy"),
                            ("RETURN_TO_VENDOR", "Return to Vendor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_book_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "disposal_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "disposal_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("approval_remarks", models.TextField(blank=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_details",
                    models.TextField(blank=True, help_text="Buyer information if sold"),
                ),
                (
                    "disposal_document",
                    models.FileField(
                        blank=True, null=True, upload_to="disposal_documents/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Disposal",
                "verbose_name_plural": "Asset Disposals",
                "db_table": "asset_disposals",
                "ordering": ["-requested_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("transfer_number", models.CharField(max_length=50, unique=True)),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("approval_remarks", models.TextField(blank=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "transfer_document",
                    models.FileField(
                        blank=True, null=True, upload_to="transfer_documents/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Transfer",
                "verbose_name_plural": "Asset Transfers",
                "db_table": "asset_transfers",
                "ordering": ["-requested_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ["company", "-created_at"],
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="assetcategory",
            options={
                "ordering": ["company", "name"],
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="assettype",
            options={
                "ordering": ["company", "category", "name"],
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ["company", "name"],
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
            },
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_asset_t_3d9023_idx",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_serial__240171_idx",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_status_326766_idx",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_locatio_94b79f_idx",
        ),
        migrations.AddField(
            model_name="asset",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_categories",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assettype",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_types",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_tag",
            field=models.CharField(
                db_index=True, help_text="Unique asset identifier", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="assettype",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("company", "asset_tag")},
        ),
        migrations.AlterUniqueTogether(
            name="assetcategory",
            unique_together={("company", "code"), ("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="assettype",
            unique_together={("company", "code"), ("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="vendor",
            unique_together={("company", "code"), ("company", "name")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "asset_tag"], name="assets_company_85a771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "serial_number"], name="assets_company_973916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "status"], name="assets_company_0cdbfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "location", "department"],
                name="assets_company_1120a6_idx",
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disposal_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposals",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disposal_completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetdisposal",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disposal_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="from_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="from_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="to_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_to",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="to_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_to",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="assettransfer",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(
                fields=["status", "-requested_date"],
                name="asset_dispo_status_4ae086_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetdisposal",
            index=models.Index(
                fields=["asset", "-requested_date"],
                name="asset_dispo_asset_i_733236_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["status", "-requested_date"],
                name="asset_trans_status_e4c357_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["asset", "-requested_date"],
                name="asset_trans_asset_i_c1dfc6_idx",
            ),
        ),
    ]
