# Generated by Django 6.0.1 on 2026-02-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_assetdisposal_assettransfer_alter_asset_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assettype",
            name="category_type",
        ),
    ]
