# Generated by Django 6.0.1 on 2026-02-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancerequest",
            options={
                "ordering": ["company", "-requested_date"],
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancetype",
            options={
                "ordering": ["company", "name"],
                "verbose_name": "Maintenance Type",
                "verbose_name_plural": "Maintenance Types",
            },
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maintenancetype",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_types",
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="request_number",
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="maintenancerequest",
            unique_together={("company", "request_number")},
        ),
        migrations.AlterUniqueTogether(
            name="maintenancetype",
            unique_together={("company", "code"), ("company", "name")},
        ),
    ]
